import { useEffect, useMemo, useState } from "react";
import { createAutomation, deleteAutomation, updateAutomation, watchStudioState } from "../lib/studioRepository";
import { runStudioAutomation } from "../lib/studioApi";
import { useToast } from "../context/ToastContext";

const empty = { profileId: "", contentTypeId: "", name: "", scheduleType: "interval", intervalMinutes: 360, approvalMode: "review", maxItemsPerRun: 1, source: "", rssUrls: "", localFolder: "", selectionRule: "oldest", destinations: "", destinationAccountIds: [] };
export default function Automations() {
  const [state, setState] = useState({ profiles: [], contentTypes: [], automations: [] }); const [form, setForm] = useState(empty); const [editingId, setEditingId] = useState(null); const [runningId, setRunningId] = useState(null); const [lastRun, setLastRun] = useState(null); const toast = useToast();
  useEffect(() => watchStudioState(setState), []);
  const profile = useMemo(() => state.profiles.find(x=>x.id===form.profileId), [state.profiles, form.profileId]);
  async function save(e) { e.preventDefault(); try { const payload = { profileId: form.profileId, contentTypeId: form.contentTypeId, name: form.name, scheduleType: form.scheduleType, scheduleConfig: { intervalMinutes: Number(form.intervalMinutes) || 360 }, approvalMode: form.approvalMode, maxItemsPerRun: Number(form.maxItemsPerRun) || 1, sourceConfig: { description: form.source, rssUrls: form.rssUrls.split(",").map(x=>x.trim()).filter(Boolean), localFolder: form.localFolder.trim(), selectionRule: form.selectionRule }, destinations: form.destinations.split(",").map(x=>x.trim()).filter(Boolean), destinationAccountIds: form.destinationAccountIds, timezone: profile?.timezone }; if (editingId) await updateAutomation(editingId,payload); else await createAutomation(payload); toast.success(editingId ? "Automation updated." : "Automation created."); setEditingId(null); setForm(empty); } catch(error) { toast.error(error.message || "Could not save automation."); } }
  function edit(item) { setEditingId(item.id); setForm({ ...empty, ...item, intervalMinutes: item.scheduleConfig?.intervalMinutes || 360, source: item.sourceConfig?.description || "", rssUrls: (item.sourceConfig?.rssUrls || []).join(", "), localFolder: item.sourceConfig?.localFolder || "", selectionRule: item.sourceConfig?.selectionRule || "oldest", destinations: (item.destinations || []).join(", "), destinationAccountIds: item.destinationAccountIds || [] }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function remove(item) { if (!window.confirm("Delete " + item.name + "?")) return; try { await deleteAutomation(item.id); toast.success("Automation deleted."); } catch (error) { toast.error(error.message || "Could not delete automation."); } }
  async function runNow(item) { setRunningId(item.id); setLastRun(null); try { const result = await runStudioAutomation(item.id); setLastRun(result); toast.success("Automation generated content."); } catch (error) { toast.error(error.message || "Automation run failed."); } finally { setRunningId(null); } }
  return <div className="max-w-6xl">
    <header className="mb-8"><p className="label">Content system · 03</p><h1 className="font-display text-3xl font-semibold tracking-tight">Automations</h1><p className="text-muted text-sm mt-1">Connect a profile to a reusable content type, schedule it, and choose where the result should go.</p></header>
    {!state.profiles.length && <div className="card p-5 mb-6 border-amber/30"><p className="font-medium text-sm">Create a profile first.</p><a href="#/profiles" className="text-xs text-teal hover:underline">Open Profiles →</a></div>}
    <form onSubmit={save} className="card p-6 md:p-8 mb-8"><div className="grid md:grid-cols-2 gap-4">
      <label><span className="label">Page / profile</span><select className="input" required value={form.profileId} onChange={e=>setForm({...form,profileId:e.target.value})}><option value="">Select profile</option>{state.profiles.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
      <label><span className="label">Content type</span><select className="input" required value={form.contentTypeId} onChange={e=>setForm({...form,contentTypeId:e.target.value})}><option value="">Select content type</option>{state.contentTypes.filter(x=>x.active).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
      <label><span className="label">Automation name</span><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Future Tech · Tech News Image" /></label>
      <label><span className="label">Schedule</span><select className="input" value={form.scheduleType} onChange={e=>setForm({...form,scheduleType:e.target.value})}><option value="interval">Every X minutes</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="manual">Manual only</option></select></label>
      {form.scheduleType === "interval" && <label><span className="label">Interval minutes</span><input className="input" type="number" min="1" value={form.intervalMinutes} onChange={e=>setForm({...form,intervalMinutes:e.target.value})} /></label>}
      <label><span className="label">Approval mode</span><select className="input" value={form.approvalMode} onChange={e=>setForm({...form,approvalMode:e.target.value})}><option value="auto">Auto publish</option><option value="review">Review before publish</option><option value="generate">Generate only</option></select></label>
      <label><span className="label">Items per run</span><input className="input" type="number" min="1" value={form.maxItemsPerRun} onChange={e=>setForm({...form,maxItemsPerRun:e.target.value})} /></label>
      <label><span className="label">Source</span><input className="input" value={form.source} onChange={e=>setForm({...form,source:e.target.value})} placeholder="RSS feeds / local folder / API..." /></label><label><span className="label">RSS feed URLs</span><input className="input" value={form.rssUrls} onChange={e=>setForm({...form,rssUrls:e.target.value})} placeholder="https://example.com/feed.xml, https://example.com/rss" /><p className="text-[10px] text-muted mt-1">Used by the native Tech News Image runner.</p></label><label><span className="label">Local media folder</span><input className="input" value={form.localFolder} onChange={e=>setForm({...form,localFolder:e.target.value})} placeholder="videos/viral" /><p className="text-[10px] text-muted mt-1">Folder inside MEDIA_ROOT for Local Video automations.</p></label><label><span className="label">Video selection</span><select className="input" value={form.selectionRule} onChange={e=>setForm({...form,selectionRule:e.target.value})}><option value="oldest">Oldest first</option><option value="newest">Newest first</option><option value="random">Random unused</option></select></label>
      <label className="md:col-span-2"><span className="label">Publishing destinations</span>{state.accounts?.length ? <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">{state.accounts.map(account => { const checked=form.destinationAccountIds.includes(account.id); return <label key={account.id} className={"flex items-center gap-2 rounded-xl border px-3 py-2 cursor-pointer " + (checked ? "border-teal/40 bg-teal/5" : "border-border hover:border-violet/30")}><input type="checkbox" checked={checked} onChange={e=>setForm({...form,destinationAccountIds:e.target.checked ? [...form.destinationAccountIds,account.id] : form.destinationAccountIds.filter(id=>id!==account.id),destinations:e.target.checked ? [...form.destinations.split(",").map(x=>x.trim()).filter(Boolean),account.name].join(", ") : form.destinations.split(",").filter(x=>x.trim()!==account.name).join(", ")})} /><span><span className="block text-xs font-medium">{account.name}</span><span className="block text-[10px] text-muted">{account.platform} · {account.status}</span></span></label> })}</div> : <div className="rounded-xl border border-dashed border-border p-4 text-xs text-muted">No Studio destination accounts yet. <a className="text-teal hover:underline" href="#/accounts">Add accounts →</a></div>}</label>
    </div>{profile && <div className="mt-5 rounded-xl border border-border bg-black/10 p-4 text-xs"><span className="text-muted">Profile master prompt:</span> <span className="text-ivory">{profile.masterPrompt ? "Attached" : "Not configured"}</span></div>}<div className="flex gap-2 mt-6"><button className="btn-primary">{editingId ? "Save automation" : "Create automation"}</button>{editingId && <button type="button" className="btn-ghost text-xs" onClick={()=>{setEditingId(null);setForm(empty)}}>Cancel</button>}</div></form>
    {lastRun && <div className="card p-5 mb-6 border-teal/20"><p className="label mb-2">Last native run</p><p className="font-semibold">{lastRun.title}</p><p className="text-sm text-muted mt-2 whitespace-pre-wrap">{lastRun.caption}</p><div className="flex flex-wrap gap-2 mt-3"><span className="text-[10px] font-mono px-2 py-1 rounded-full border border-teal/30 text-teal">{lastRun.status}</span>{lastRun.source?.sourceName && <span className="text-[10px] font-mono px-2 py-1 rounded-full border border-border text-muted">{lastRun.source.sourceName}</span>}{lastRun.media?.url && <a className="text-[10px] font-mono px-2 py-1 rounded-full border border-violet/30 text-violet hover:bg-violet/10" href={(import.meta.env.VITE_SERVER_URL || "http://localhost:8787") + lastRun.media.url} target="_blank" rel="noreferrer">view image ↗</a>}</div></div>}\n    <div className="grid gap-4">{state.automations.length === 0 ? <div className="card p-8"><p className="font-medium">No automations configured.</p><p className="text-sm text-muted mt-1">Create one to connect your first page to a content recipe.</p></div> : state.automations.map(item=>{ const p=state.profiles.find(x=>x.id===item.profileId); const t=state.contentTypes.find(x=>x.id===item.contentTypeId); return <article key={item.id} className="card p-5 flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={item.enabled ? "text-[10px] font-mono px-2 py-1 rounded-full border border-teal/30 text-teal bg-teal/5" : "text-[10px] font-mono px-2 py-1 rounded-full border border-border text-muted"}>{item.enabled ? "ACTIVE" : "PAUSED"}</span><span className="text-xs text-muted">{p?.name || "Missing profile"} → {t?.name || "Missing content type"}</span></div><h2 className="font-semibold mt-2 truncate">{item.name}</h2><p className="text-xs text-muted mt-1">{item.scheduleType === "interval" ? "Every " + (item.scheduleConfig?.intervalMinutes || 360) + " minutes" : item.scheduleType} · {item.approvalMode} · up to {item.maxItemsPerRun || 1} item(s)</p><p className="text-[11px] font-mono text-muted mt-2">{(item.destinations || []).join(" · ") || "No destinations yet"}</p></div><div className="flex gap-2 shrink-0"><button className="btn-ghost text-xs" onClick={async ()=>{try { await updateAutomation(item.id,{enabled:!item.enabled}); toast.success(item.enabled ? "Automation paused." : "Automation activated."); } catch (error) { toast.error(error.message || "Could not update automation."); }}}>{item.enabled ? "Pause" : "Activate"}</button><button className="btn-ghost text-xs" onClick={()=>edit(item)}>Edit</button><button className="text-xs text-rose hover:underline px-2" onClick={()=>remove(item)}>Delete</button></div></article>})}</div>
  </div>;
}